title:        Evaluation 'Extended-KeY-Sourceview' prototype

theme: jekyll-theme-modernist

show_downloads: true

github:
  zip_url: https://github.com/Mikescher/key-extsourceview-evaluation/blob/master/package/evaluation.zip
